[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mon-projet-swig"
version = "0.1.0"
description = "Exemple minimal de module Python utilisant C++ et SWIG"
readme = "README.md"
requires-python = ">=3.10"
authors = [
  { name = "Romain" }
]
dependencies = []

[project.urls]
Homepage = "https://example.com/mon-projet-swig"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
